// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt0eRb_fpMx8HgvlqhHYD2WhbjS9nFZcQ',
    appId: '1:472859181501:web:36df775371b082c7fd52d4',
    messagingSenderId: '472859181501',
    projectId: 'saving-goal-1e180',
    authDomain: 'saving-goal-1e180.firebaseapp.com',
    storageBucket: 'saving-goal-1e180.appspot.com',
    measurementId: 'G-JM8Z1W6LX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt9p7b8cmcUI7RgSwxC_JBxpbdp3L1joU',
    appId: '1:472859181501:android:9192b47b26f005b4fd52d4',
    messagingSenderId: '472859181501',
    projectId: 'saving-goal-1e180',
    storageBucket: 'saving-goal-1e180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfjtb7sa4HPtCaDlK00Uh8ICSnNOCGr0s',
    appId: '1:472859181501:ios:c6a69f2aca828e5afd52d4',
    messagingSenderId: '472859181501',
    projectId: 'saving-goal-1e180',
    storageBucket: 'saving-goal-1e180.appspot.com',
    iosBundleId: 'com.example.savingGoal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfjtb7sa4HPtCaDlK00Uh8ICSnNOCGr0s',
    appId: '1:472859181501:ios:c6a69f2aca828e5afd52d4',
    messagingSenderId: '472859181501',
    projectId: 'saving-goal-1e180',
    storageBucket: 'saving-goal-1e180.appspot.com',
    iosBundleId: 'com.example.savingGoal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt0eRb_fpMx8HgvlqhHYD2WhbjS9nFZcQ',
    appId: '1:472859181501:web:aa8b00e91621b182fd52d4',
    messagingSenderId: '472859181501',
    projectId: 'saving-goal-1e180',
    authDomain: 'saving-goal-1e180.firebaseapp.com',
    storageBucket: 'saving-goal-1e180.appspot.com',
    measurementId: 'G-L3E3PM59PJ',
  );

}