name: Flutter CI/CD with Firebase

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Flutter APK
      run: flutter build apk --release

    # Optionally, upload the APK as a build artifact
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Deploy to Firebase App Distribution
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      run: firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app 1:472859181501:android:9192b47b26f005b4fd52d4 --groups qa-team
